name: Laura Dapito
favicon: null
layout_spectrum: 0.1301585086621344
typography_spectrum: 0.9848614973016083
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8456556322053075
  lightness: 0.19782923767343163
  saturation: 0.4375
  rhythmicContrast: 0.933357477420941
purpose: []
